FROM node:20-alpine
WORKDIR /app

#  manifests
COPY package.json package-lock.json* ./

# tailwind/postcss/autoprefixer)
ENV NODE_ENV=development
RUN npm install

# sources seront montées par le volumeeee
EXPOSE 5173

# Fuck u listen
CMD ["npm","run","dev","--","--host","0.0.0.0"]
