services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: basset
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: bassetbot
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U basset -d bassetbot"]
      interval: 5s
      timeout: 5s
      retries: 10
  backend:
    build: ./backend
    env_file: [./backend/.env]
    environment:
      DATABASE_URL: postgresql+psycopg2://basset:secret@db:5432/bassetbot
      LOG_LEVEL: info
      MODEL_NAME: ${MODEL_NAME:-gpt-4o-mini}
      ALLOWED_ORIGINS: http://localhost:5173
    depends_on:
      db:
        condition: service_healthy
    ports: ["8000:8000"]
    volumes:
      - ./backend/app:/app/app
      - ./backend/alembic:/app/alembic
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    environment:
      VITE_API_BASE: http://localhost:8000/api
    ports: ["5173:5173"]
    volumes:
      - ./frontend:/app
      - /app/node_modules
volumes:
  db_data:
